changelog:
  categories:
    - title: Features
      labels:
        - feat
      types:
        - feat
    - title: Bug Fixes
      labels:
        - fix
      types:
        - fix
    - title: Performance
      types:
        - perf
    - title: Reverts
      types:
        - revert
