/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    'payload-mcp-api-keys': PayloadMcpApiKeyAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    insights: Insight;
    media: Media;
    categories: Category;
    users: User;
    partners: Partner;
    machines: Machine;
    'machine-tags': MachineTag;
    faqItems: FaqItem;
    projects: Project;
    brands: Brand;
    claims: Claim;
    consentLogs: ConsentLog;
    redirects: Redirect;
    forms: Form;
    'form-submissions': FormSubmission;
    search: Search;
    'payload-mcp-api-keys': PayloadMcpApiKey;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-folders': FolderInterface;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    'machine-tags': {
      machines: 'machines';
    };
    'payload-folders': {
      documentsAndFolders: 'payload-folders' | 'media';
    };
  };
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    insights: InsightsSelect<false> | InsightsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    partners: PartnersSelect<false> | PartnersSelect<true>;
    machines: MachinesSelect<false> | MachinesSelect<true>;
    'machine-tags': MachineTagsSelect<false> | MachineTagsSelect<true>;
    faqItems: FaqItemsSelect<false> | FaqItemsSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    brands: BrandsSelect<false> | BrandsSelect<true>;
    claims: ClaimsSelect<false> | ClaimsSelect<true>;
    consentLogs: ConsentLogsSelect<false> | ConsentLogsSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    search: SearchSelect<false> | SearchSelect<true>;
    'payload-mcp-api-keys': PayloadMcpApiKeysSelect<false> | PayloadMcpApiKeysSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-folders': PayloadFoldersSelect<false> | PayloadFoldersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'es') | ('en' | 'es')[];
  globals: {
    header: Header;
    footer: Footer;
    settings: Setting;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    settings: SettingsSelect<false> | SettingsSelect<true>;
  };
  locale: 'en' | 'es';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User | PayloadMcpApiKey;
  jobs: {
    tasks: {
      syncClaimToIntegration: TaskSyncClaimToIntegration;
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface PayloadMcpApiKeyAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  hero: {
    type: 'none' | 'highImpact' | 'mediumImpact' | 'lowImpact' | 'simple';
    richText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    links?:
      | {
          link: {
            type?: ('reference' | 'custom' | 'modal') | null;
            newTab?: boolean | null;
            reference?:
              | ({
                  relationTo: 'pages';
                  value: number | Page;
                } | null)
              | ({
                  relationTo: 'insights';
                  value: number | Insight;
                } | null);
            url?: string | null;
            /**
             * Opens this form in a modal drawer instead of navigating.
             */
            modalForm?: (number | null) | Form;
            label: string;
            /**
             * Choose how the link should be rendered.
             */
            appearance?: ('default' | 'outline' | 'ghost') | null;
          };
          id?: string | null;
        }[]
      | null;
    /**
     * For highImpact: used as video poster and img fallback. For mediumImpact: right-column image.
     */
    media?: (number | null) | Media;
    /**
     * Optional. MP4 recommended. Plays muted + looped over the poster image.
     */
    backgroundVideo?: (number | null) | Media;
    tags?:
      | {
          label: string;
          id?: string | null;
        }[]
      | null;
  };
  layout?:
    | (
        | CallToActionBlock
        | ContentBlock
        | MediaBlock
        | ArchiveBlock
        | FormBlock
        | CardGridBlock
        | MetricsBlock
        | TrustStripBlock
        | AudienceShowcaseBlock
        | InsightsShowcaseBlock
        | ProjectsShowcaseBlock
        | FormatsGridBlock
        | MachinesListingBlock
        | ProcessStepsBlock
        | StatementBlock
        | FAQWithFormBlock
        | ClaimFormBlock
        | SupportHubBlock
      )[]
    | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  parent?: (number | null) | Page;
  breadcrumbs?:
    | {
        doc?: (number | null) | Page;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "insights".
 */
export interface Insight {
  id: number;
  title: string;
  heroImage?: (number | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  relatedPosts?: (number | Insight)[] | null;
  categories?: (number | Category)[] | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  /**
   * Show this insight in the Insights Showcase block on the home page.
   */
  featured?: boolean | null;
  publishedAt?: string | null;
  authors?: (number | User)[] | null;
  populatedAuthors?:
    | {
        id?: string | null;
        name?: string | null;
      }[]
    | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  folder?: (number | null) | FolderInterface;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    square?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    xlarge?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders".
 */
export interface FolderInterface {
  id: number;
  name: string;
  folder?: (number | null) | FolderInterface;
  documentsAndFolders?: {
    docs?: (
      | {
          relationTo?: 'payload-folders';
          value: number | FolderInterface;
        }
      | {
          relationTo?: 'media';
          value: number | Media;
        }
    )[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  folderType?: 'media'[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  parent?: (number | null) | Category;
  breadcrumbs?:
    | {
        doc?: (number | null) | Category;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            /**
             * Monday.com column id this field's value maps to (e.g. "text7", "dropdown0"). Leave blank to exclude this field from the sync.
             */
            externalId?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            /**
             * Monday.com column id this field's value maps to (e.g. "text7", "dropdown0"). Leave blank to exclude this field from the sync.
             */
            externalId?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            /**
             * Monday.com column id this field's value maps to (e.g. "text7", "dropdown0"). Leave blank to exclude this field from the sync.
             */
            externalId?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            /**
             * Monday.com column id this field's value maps to (e.g. "text7", "dropdown0"). Leave blank to exclude this field from the sync.
             */
            externalId?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            /**
             * Monday.com column id this field's value maps to (e.g. "text7", "dropdown0"). Leave blank to exclude this field from the sync.
             */
            externalId?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            /**
             * Monday.com column id this field's value maps to (e.g. "text7", "dropdown0"). Leave blank to exclude this field from the sync.
             */
            externalId?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            /**
             * Monday.com column id this field's value maps to (e.g. "text7", "dropdown0"). Leave blank to exclude this field from the sync.
             */
            externalId?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            /**
             * Monday.com column id this field's value maps to (e.g. "text7", "dropdown0"). Leave blank to exclude this field from the sync.
             */
            externalId?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
        | {
            name: string;
            label?: string | null;
            uploadCollection: 'media';
            mimeTypes?:
              | {
                  mimeType: string;
                  id?: string | null;
                }[]
              | null;
            width?: number | null;
            maxFileSize?: number | null;
            required?: boolean | null;
            multiple?: boolean | null;
            /**
             * Monday.com column id this field's value maps to (e.g. "text7", "dropdown0"). Leave blank to exclude this field from the sync.
             */
            externalId?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'upload';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  /**
   * External system this form syncs submissions to. Odoo is not yet implemented — reserved for when that integration is ready.
   */
  integrationTarget?: ('none' | 'monday' | 'odoo') | null;
  /**
   * The Monday.com board id (or future Odoo record id) this form syncs to.
   */
  externalId?: string | null;
  /**
   * Monday.com group id within the board (e.g. "topics").
   */
  mondayGroupId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock".
 */
export interface CallToActionBlock {
  richText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  links?:
    | {
        link: {
          type?: ('reference' | 'custom' | 'modal') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'insights';
                value: number | Insight;
              } | null);
          url?: string | null;
          /**
           * Opens this form in a modal drawer instead of navigating.
           */
          modalForm?: (number | null) | Form;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock".
 */
export interface ContentBlock {
  columns?:
    | {
        size?: ('oneThird' | 'half' | 'twoThirds' | 'full') | null;
        richText?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        enableLink?: boolean | null;
        link?: {
          type?: ('reference' | 'custom' | 'modal') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'insights';
                value: number | Insight;
              } | null);
          url?: string | null;
          /**
           * Opens this form in a modal drawer instead of navigating.
           */
          modalForm?: (number | null) | Form;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'content';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock".
 */
export interface MediaBlock {
  media: number | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock".
 */
export interface ArchiveBlock {
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  populateBy?: ('collection' | 'selection') | null;
  relationTo?: 'insights' | null;
  categories?: (number | Category)[] | null;
  limit?: number | null;
  selectedDocs?:
    | {
        relationTo: 'insights';
        value: number | Insight;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'archive';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock".
 */
export interface FormBlock {
  form: number | Form;
  enableIntro?: boolean | null;
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'formBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CardGridBlock".
 */
export interface CardGridBlock {
  variant: 'compact' | 'icon' | 'pillar';
  /**
   * Small label above the heading, e.g. "WHERE IT WORKS"
   */
  eyebrow?: string | null;
  /**
   * Para destacar una palabra o frase en negrita, envuélvela en asteriscos dobles: **texto**
   */
  heading: string;
  /**
   * Optional text below the heading. Used in compact and pillar variants.
   */
  subheading?: string | null;
  /**
   * Optional button shown below cards. Used in pillar variant.
   */
  link?: {
    label?: string | null;
    url?: string | null;
    type?: ('custom' | 'reference') | null;
    reference?: (number | null) | Page;
  };
  items?:
    | {
        /**
         * Optional image shown at the top of the card.
         */
        media?: (number | null) | Media;
        /**
         * Small label above the card title. Used in pillar variant.
         */
        eyebrow?: string | null;
        /**
         * Icon identifier. Used in icon variant.
         */
        icon?: string | null;
        title: string;
        body?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        /**
         * Optional CTA link per card. Used in icon variant.
         */
        link?: {
          label?: string | null;
          url?: string | null;
          type?: ('custom' | 'reference') | null;
          reference?: (number | null) | Page;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cardGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MetricsBlock".
 */
export interface MetricsBlock {
  /**
   * Small label above the heading, e.g. "WHY AMERIKIOSKS"
   */
  eyebrow?: string | null;
  /**
   * Para destacar una palabra o frase en negrita, envuélvela en asteriscos dobles: **texto**
   */
  heading: string;
  items?:
    | {
        /**
         * e.g. "10+", "1000+", "30"
         */
        value: string;
        /**
         * e.g. "Years of Industry Experience"
         */
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional CTA button shown below the stats. Can link to a page, a custom URL, or open a form in a modal.
   */
  links?:
    | {
        link: {
          type?: ('reference' | 'custom' | 'modal') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'insights';
                value: number | Insight;
              } | null);
          url?: string | null;
          /**
           * Opens this form in a modal drawer instead of navigating.
           */
          modalForm?: (number | null) | Form;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'metrics';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TrustStripBlock".
 */
export interface TrustStripBlock {
  /**
   * Small label above the heading, e.g. "WHO WE WORK WITH"
   */
  eyebrow?: string | null;
  /**
   * Para destacar una palabra o frase en negrita, envuélvela en asteriscos dobles: **texto**
   */
  heading: string;
  /**
   * Optional text below the heading.
   */
  subheading?: string | null;
  /**
   * Max number of partners to show. 0 = show all.
   */
  limit?: number | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'trustStrip';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AudienceShowcaseBlock".
 */
export interface AudienceShowcaseBlock {
  /**
   * Small label above heading, e.g. "WHO IT'S FOR"
   */
  eyebrow?: string | null;
  /**
   * Para destacar una palabra o frase en negrita, envuélvela en asteriscos dobles: **texto**
   */
  heading: string;
  subheading?: string | null;
  items?:
    | {
        /**
         * Pulls title and description from this page.
         */
        page: number | Page;
        /**
         * Card background image.
         */
        image: number | Media;
        /**
         * Overrides the card title. If not set, defaults to the linked page title.
         */
        label?: string | null;
        /**
         * Overrides the card description. If not set, defaults to the linked page SEO description.
         */
        description?: string | null;
        /**
         * CTA link label, e.g. "Explore brand programs"
         */
        cta?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'audienceShowcase';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "InsightsShowcaseBlock".
 */
export interface InsightsShowcaseBlock {
  /**
   * Small label above heading, e.g. "INSIGHTS"
   */
  eyebrow?: string | null;
  /**
   * Para destacar una palabra o frase en negrita, envuélvela en asteriscos dobles: **texto**
   */
  heading: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'insightsShowcase';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProjectsShowcaseBlock".
 */
export interface ProjectsShowcaseBlock {
  /**
   * Small label above heading, e.g. "REAL BRAND MOMENTS"
   */
  eyebrow?: string | null;
  /**
   * Para destacar una palabra o frase en negrita, envuélvela en asteriscos dobles: **texto**
   */
  heading: string;
  /**
   * Supporting text shown below the heading
   */
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Fetch projects where tags.label matches this value, e.g. "brand", "agency"
   */
  filterTag: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'projectsShowcase';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormatsGridBlock".
 */
export interface FormatsGridBlock {
  /**
   * Small label above heading, e.g. "FORMATS"
   */
  eyebrow?: string | null;
  /**
   * Para destacar una palabra o frase en negrita, envuélvela en asteriscos dobles: **texto**
   */
  heading: string;
  subheading?: string | null;
  /**
   * Show machines matching these tags. Leave empty to show all. Ignored if items are set.
   */
  filterTags?: (number | MachineTag)[] | null;
  /**
   * Explicit machine picks. Overrides filterTags.
   */
  items?:
    | {
        machine: number | Machine;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'formatsGrid';
}
/**
 * Reusable tags for filtering — used by Machines and the Formats Grid block.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "machine-tags".
 */
export interface MachineTag {
  id: number;
  label: string;
  /**
   * Machines currently using this tag — read-only, for spotting unused tags.
   */
  machines?: {
    docs?: (number | Machine)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "machines".
 */
export interface Machine {
  id: number;
  name: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  /**
   * Short label shown on cards, e.g. "Full-size branded machine"
   */
  tagline?: string | null;
  /**
   * Small kicker above the hero title, e.g. "NEXT GENERATION"
   */
  heroEyebrow?: string | null;
  image: number | Media;
  /**
   * e.g. full-size, compact, campaign, premium — used for block-level filtering
   */
  tags?: (number | MachineTag)[] | null;
  gallery?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  cta?: {
    label?: string | null;
    url?: string | null;
  };
  /**
   * Optional downloadable brochure (PDF). Hides the "Download brochure" hero button when empty.
   */
  brochure?: (number | null) | Media;
  highlights?: {
    /**
     * e.g. "WHY GAMMA 13"
     */
    eyebrow?: string | null;
    /**
     * e.g. "Engineered for performance. Designed for any location."
     */
    heading?: string | null;
    items?:
      | {
          /**
           * Material Symbols icon name, e.g. "inventory_2"
           */
          icon?: string | null;
          title: string;
          description?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  capabilities?: {
    /**
     * e.g. "Built for scale. Designed for ease."
     */
    heading?: string | null;
    items?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  dimensions?: {
    /**
     * e.g. 92"
     */
    height?: string | null;
    /**
     * e.g. 74"
     */
    width?: string | null;
    /**
     * e.g. 40"
     */
    depth?: string | null;
  };
  /**
   * Labeled technical line-drawings (e.g. front, side, isometric views)
   */
  dimensionDiagrams?:
    | {
        image: number | Media;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Show the full rotation-scrub hero instead of the default zoom+fade hero.
   */
  useRotationHero?: boolean | null;
  /**
   * Ordered turntable frames (e.g. 60-120 images, 0-360°). Required when "useRotationHero" is checked.
   */
  rotationFrames?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MachinesListingBlock".
 */
export interface MachinesListingBlock {
  /**
   * How many machines to show per page.
   */
  itemsPerPage?: number | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'machinesListing';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProcessStepsBlock".
 */
export interface ProcessStepsBlock {
  /**
   * Small label above heading, e.g. "HOW IT WORKS"
   */
  eyebrow?: string | null;
  /**
   * Para destacar una palabra o frase en negrita, envuélvela en asteriscos dobles: **texto**
   */
  heading: string;
  subheading?: string | null;
  steps: {
    title: string;
    body?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    id?: string | null;
  }[];
  cta?:
    | {
        link: {
          type?: ('reference' | 'custom' | 'modal') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'insights';
                value: number | Insight;
              } | null);
          url?: string | null;
          /**
           * Opens this form in a modal drawer instead of navigating.
           */
          modalForm?: (number | null) | Form;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'processSteps';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatementBlock".
 */
export interface StatementBlock {
  /**
   * Small label above the statement, e.g. "Our Philosophy"
   */
  eyebrow?: string | null;
  /**
   * The single sentence shown large, e.g. "The right brand, in the right place, at the right moment." Para destacar una palabra en negrita, envuélvela en asteriscos dobles: **texto**
   */
  statement: string;
  /**
   * Optional supporting text below the statement.
   */
  subheading?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'statement';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FAQWithFormBlock".
 */
export interface FAQWithFormBlock {
  /**
   * Small label above heading, e.g. "START A PROGRAM"
   */
  eyebrow?: string | null;
  /**
   * Para destacar una palabra o frase en negrita, envuélvela en asteriscos dobles: **texto**
   */
  heading: string;
  subheading?: string | null;
  /**
   * Pull FAQItems matching these tags, sorted by weight descending.
   */
  filterTags: {
    tag: string;
    id?: string | null;
  }[];
  /**
   * Payload form to render in the form panel (use Forms collection)
   */
  form: number | Form;
  id?: string | null;
  blockName?: string | null;
  blockType: 'faqWithForm';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ClaimFormBlock".
 */
export interface ClaimFormBlock {
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Shown to cash-refund customers who confirm the machine still shows an available credit — no refund is needed yet.
   */
  creditsAvailableYesMessage?: string | null;
  /**
   * Shown to cash-refund customers who confirm the credit is gone, before they continue into the refund form.
   */
  creditsAvailableNoMessage?: string | null;
  additionalInfoHint?: string | null;
  submitButtonLabel?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'claimForm';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SupportHubBlock".
 */
export interface SupportHubBlock {
  /**
   * E.164 format, e.g. +18885093699
   */
  phoneNumber: string;
  /**
   * E.164 format, e.g. +18885093699
   */
  whatsappNumber: string;
  refundFormUrl: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'supportHub';
}
/**
 * Client/venue logos shown in the trust strip on the homepage (e.g. Hilton, Royal Caribbean, CVS). Not related to Brands.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners".
 */
export interface Partner {
  id: number;
  name: string;
  logo: number | Media;
  /**
   * Lower number appears first. Use 1, 2, 3… to control display order.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqItems".
 */
export interface FaqItem {
  id: number;
  question: string;
  answer: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Higher weight appears first. Use multiples of 10 (10, 20, 30…) so items can be inserted between existing ones.
   */
  weight?: number | null;
  /**
   * e.g. brands, venues, replenishment, branding, pricing
   */
  tags?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  /**
   * Eyebrow label shown on cards, e.g. "FAN STAND"
   */
  category?: string | null;
  /**
   * Short text shown on the card
   */
  description?: string | null;
  image: number | Media;
  /**
   * Used to filter projects in blocks, e.g. "brand"
   */
  tags?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Client brands/product lines sold through Amerikiosks machines (e.g. Carlo's Bakery, Pharmabox by CVS) — referenced by Claims.kioskBrand, populates the brand picker on the refund claim form. Not the machine hardware (see Machines) or homepage trust-strip logos (see Partners).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands".
 */
export interface Brand {
  id: number;
  name: string;
  logo?: (number | null) | Media;
  /**
   * Lower number appears first. Use 1, 2, 3… to control display order.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Refund/complaint claims submitted from the customer-service QR flow on deployed kiosks.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "claims".
 */
export interface Claim {
  id: number;
  /**
   * Which client brand/product line was being purchased (e.g. Carlo's Bakery).
   */
  kioskBrand: number | Brand;
  paymentMethod: 'card' | 'cash' | 'google_pay' | 'apple_pay';
  customerFirstName: string;
  customerLastName: string;
  customerEmail: string;
  customerPhone: string;
  transactionDateTime: string;
  /**
   * Free-text reference for where the issue happened (state, city, property name) — not a structured address.
   */
  location: string;
  claimReason: 'partial_dispense' | 'damaged_product' | 'wrong_product' | 'no_product';
  additionalInfo?: string | null;
  /**
   * Last 4 digits of the card used, if payment method was card.
   */
  lastFourCardDigits?: string | null;
  /**
   * Only relevant for cash refunds (card refunds go back to the card automatically). Values match JotForm's "Select a refund method" options verbatim.
   */
  refundMethod?: ('Zelle' | 'CashApp' | 'Paypal' | 'Venmo') | null;
  /**
   * Username/email/phone associated with the refund method account above.
   */
  refundAccount?: string | null;
  /**
   * Optional staff-attached photo (authenticated admin only). Public claim submissions never populate this field — see photoKey below for the customer-submitted photo.
   */
  photo?: (number | null) | Media;
  /**
   * Object key of the customer-submitted photo in the private R2 bucket (see src/utilities/privateUpload.ts) — never a public URL. Fetch GET /api/claims/:id/photo-url (authenticated) to view it; the URL that returns expires in 15 minutes.
   */
  photoKey?: string | null;
  /**
   * Captured from the QR code scan (machine_id query param), for internal reference.
   */
  machineId?: string | null;
  /**
   * Where this claim syncs to. Set automatically from Settings → Default Claim Integration Target when the claim is created; changing it here only affects a future re-sync, not one already dispatched.
   */
  integrationTarget?: ('jotform' | 'odoo' | 'monday') | null;
  syncStatus?: ('pending' | 'synced' | 'error') | null;
  syncError?: string | null;
  syncedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "consentLogs".
 */
export interface ConsentLog {
  id: number;
  consentId: string;
  analytics: boolean;
  policyVersion?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  /**
   * You will need to rebuild the website when changing this field.
   */
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'insights';
          value: number | Insight;
        } | null);
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  form: number | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  submissionUploads?:
    | {
        field: string;
        value: {
          relationTo: 'media';
          value: number | Media;
        }[];
        id?: string | null;
      }[]
    | null;
  syncStatus?: ('pending' | 'synced' | 'error') | null;
  syncError?: string | null;
  syncedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This is a collection of automatically created search results. These results are used by the global site search and will be updated automatically as documents in the CMS are created or updated.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search".
 */
export interface Search {
  id: number;
  title?: string | null;
  priority?: number | null;
  doc: {
    relationTo: 'insights';
    value: number | Insight;
  };
  slug?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  categories?:
    | {
        relationTo?: string | null;
        categoryID?: string | null;
        title?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * API keys control which collections, resources, tools, and prompts MCP clients can access
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-mcp-api-keys".
 */
export interface PayloadMcpApiKey {
  id: number;
  /**
   * The user that the API key is associated with.
   */
  user: number | User;
  /**
   * A useful label for the API key.
   */
  label?: string | null;
  /**
   * The purpose of the API key.
   */
  description?: string | null;
  machines?: {
    /**
     * Allow clients to find machines.
     */
    find?: boolean | null;
    /**
     * Allow clients to create machines.
     */
    create?: boolean | null;
    /**
     * Allow clients to update machines.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete machines.
     */
    delete?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  collection: 'payload-mcp-api-keys';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'syncClaimToIntegration' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'syncClaimToIntegration' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'insights';
        value: number | Insight;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'partners';
        value: number | Partner;
      } | null)
    | ({
        relationTo: 'machines';
        value: number | Machine;
      } | null)
    | ({
        relationTo: 'machine-tags';
        value: number | MachineTag;
      } | null)
    | ({
        relationTo: 'faqItems';
        value: number | FaqItem;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'brands';
        value: number | Brand;
      } | null)
    | ({
        relationTo: 'claims';
        value: number | Claim;
      } | null)
    | ({
        relationTo: 'consentLogs';
        value: number | ConsentLog;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null)
    | ({
        relationTo: 'search';
        value: number | Search;
      } | null)
    | ({
        relationTo: 'payload-mcp-api-keys';
        value: number | PayloadMcpApiKey;
      } | null)
    | ({
        relationTo: 'payload-folders';
        value: number | FolderInterface;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'payload-mcp-api-keys';
        value: number | PayloadMcpApiKey;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'payload-mcp-api-keys';
        value: number | PayloadMcpApiKey;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  hero?:
    | T
    | {
        type?: T;
        richText?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    modalForm?: T;
                    label?: T;
                    appearance?: T;
                  };
              id?: T;
            };
        media?: T;
        backgroundVideo?: T;
        tags?:
          | T
          | {
              label?: T;
              id?: T;
            };
      };
  layout?:
    | T
    | {
        cta?: T | CallToActionBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
        archive?: T | ArchiveBlockSelect<T>;
        formBlock?: T | FormBlockSelect<T>;
        cardGrid?: T | CardGridBlockSelect<T>;
        metrics?: T | MetricsBlockSelect<T>;
        trustStrip?: T | TrustStripBlockSelect<T>;
        audienceShowcase?: T | AudienceShowcaseBlockSelect<T>;
        insightsShowcase?: T | InsightsShowcaseBlockSelect<T>;
        projectsShowcase?: T | ProjectsShowcaseBlockSelect<T>;
        formatsGrid?: T | FormatsGridBlockSelect<T>;
        machinesListing?: T | MachinesListingBlockSelect<T>;
        processSteps?: T | ProcessStepsBlockSelect<T>;
        statement?: T | StatementBlockSelect<T>;
        faqWithForm?: T | FAQWithFormBlockSelect<T>;
        claimForm?: T | ClaimFormBlockSelect<T>;
        supportHub?: T | SupportHubBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  generateSlug?: T;
  slug?: T;
  parent?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock_select".
 */
export interface CallToActionBlockSelect<T extends boolean = true> {
  richText?: T;
  links?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              modalForm?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock_select".
 */
export interface ContentBlockSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        size?: T;
        richText?: T;
        enableLink?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              modalForm?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock_select".
 */
export interface MediaBlockSelect<T extends boolean = true> {
  media?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock_select".
 */
export interface ArchiveBlockSelect<T extends boolean = true> {
  introContent?: T;
  populateBy?: T;
  relationTo?: T;
  categories?: T;
  limit?: T;
  selectedDocs?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock_select".
 */
export interface FormBlockSelect<T extends boolean = true> {
  form?: T;
  enableIntro?: T;
  introContent?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CardGridBlock_select".
 */
export interface CardGridBlockSelect<T extends boolean = true> {
  variant?: T;
  eyebrow?: T;
  heading?: T;
  subheading?: T;
  link?:
    | T
    | {
        label?: T;
        url?: T;
        type?: T;
        reference?: T;
      };
  items?:
    | T
    | {
        media?: T;
        eyebrow?: T;
        icon?: T;
        title?: T;
        body?: T;
        link?:
          | T
          | {
              label?: T;
              url?: T;
              type?: T;
              reference?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MetricsBlock_select".
 */
export interface MetricsBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  items?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  links?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              modalForm?: T;
              label?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TrustStripBlock_select".
 */
export interface TrustStripBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  subheading?: T;
  limit?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AudienceShowcaseBlock_select".
 */
export interface AudienceShowcaseBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  subheading?: T;
  items?:
    | T
    | {
        page?: T;
        image?: T;
        label?: T;
        description?: T;
        cta?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "InsightsShowcaseBlock_select".
 */
export interface InsightsShowcaseBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProjectsShowcaseBlock_select".
 */
export interface ProjectsShowcaseBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  body?: T;
  filterTag?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormatsGridBlock_select".
 */
export interface FormatsGridBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  subheading?: T;
  filterTags?: T;
  items?:
    | T
    | {
        machine?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MachinesListingBlock_select".
 */
export interface MachinesListingBlockSelect<T extends boolean = true> {
  itemsPerPage?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProcessStepsBlock_select".
 */
export interface ProcessStepsBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  subheading?: T;
  steps?:
    | T
    | {
        title?: T;
        body?: T;
        id?: T;
      };
  cta?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              modalForm?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatementBlock_select".
 */
export interface StatementBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  statement?: T;
  subheading?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FAQWithFormBlock_select".
 */
export interface FAQWithFormBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  subheading?: T;
  filterTags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  form?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ClaimFormBlock_select".
 */
export interface ClaimFormBlockSelect<T extends boolean = true> {
  introContent?: T;
  creditsAvailableYesMessage?: T;
  creditsAvailableNoMessage?: T;
  additionalInfoHint?: T;
  submitButtonLabel?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SupportHubBlock_select".
 */
export interface SupportHubBlockSelect<T extends boolean = true> {
  phoneNumber?: T;
  whatsappNumber?: T;
  refundFormUrl?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "insights_select".
 */
export interface InsightsSelect<T extends boolean = true> {
  title?: T;
  heroImage?: T;
  content?: T;
  relatedPosts?: T;
  categories?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  featured?: T;
  publishedAt?: T;
  authors?: T;
  populatedAuthors?:
    | T
    | {
        id?: T;
        name?: T;
      };
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        square?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        xlarge?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  parent?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners_select".
 */
export interface PartnersSelect<T extends boolean = true> {
  name?: T;
  logo?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "machines_select".
 */
export interface MachinesSelect<T extends boolean = true> {
  name?: T;
  generateSlug?: T;
  slug?: T;
  tagline?: T;
  heroEyebrow?: T;
  image?: T;
  tags?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  cta?:
    | T
    | {
        label?: T;
        url?: T;
      };
  brochure?: T;
  highlights?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        items?:
          | T
          | {
              icon?: T;
              title?: T;
              description?: T;
              id?: T;
            };
      };
  capabilities?:
    | T
    | {
        heading?: T;
        items?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  dimensions?:
    | T
    | {
        height?: T;
        width?: T;
        depth?: T;
      };
  dimensionDiagrams?:
    | T
    | {
        image?: T;
        label?: T;
        id?: T;
      };
  useRotationHero?: T;
  rotationFrames?:
    | T
    | {
        image?: T;
        id?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "machine-tags_select".
 */
export interface MachineTagsSelect<T extends boolean = true> {
  label?: T;
  machines?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqItems_select".
 */
export interface FaqItemsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  weight?: T;
  tags?:
    | T
    | {
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  category?: T;
  description?: T;
  image?: T;
  tags?:
    | T
    | {
        label?: T;
        id?: T;
      };
  body?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands_select".
 */
export interface BrandsSelect<T extends boolean = true> {
  name?: T;
  logo?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "claims_select".
 */
export interface ClaimsSelect<T extends boolean = true> {
  kioskBrand?: T;
  paymentMethod?: T;
  customerFirstName?: T;
  customerLastName?: T;
  customerEmail?: T;
  customerPhone?: T;
  transactionDateTime?: T;
  location?: T;
  claimReason?: T;
  additionalInfo?: T;
  lastFourCardDigits?: T;
  refundMethod?: T;
  refundAccount?: T;
  photo?: T;
  photoKey?: T;
  machineId?: T;
  integrationTarget?: T;
  syncStatus?: T;
  syncError?: T;
  syncedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "consentLogs_select".
 */
export interface ConsentLogsSelect<T extends boolean = true> {
  consentId?: T;
  analytics?: T;
  policyVersion?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              externalId?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              externalId?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              externalId?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              externalId?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              externalId?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              externalId?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              externalId?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              externalId?: T;
              id?: T;
              blockName?: T;
            };
        upload?:
          | T
          | {
              name?: T;
              label?: T;
              uploadCollection?: T;
              mimeTypes?:
                | T
                | {
                    mimeType?: T;
                    id?: T;
                  };
              width?: T;
              maxFileSize?: T;
              required?: T;
              multiple?: T;
              externalId?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  integrationTarget?: T;
  externalId?: T;
  mondayGroupId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  submissionUploads?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  syncStatus?: T;
  syncError?: T;
  syncedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search_select".
 */
export interface SearchSelect<T extends boolean = true> {
  title?: T;
  priority?: T;
  doc?: T;
  slug?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  categories?:
    | T
    | {
        relationTo?: T;
        categoryID?: T;
        title?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-mcp-api-keys_select".
 */
export interface PayloadMcpApiKeysSelect<T extends boolean = true> {
  user?: T;
  label?: T;
  description?: T;
  machines?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders_select".
 */
export interface PayloadFoldersSelect<T extends boolean = true> {
  name?: T;
  folder?: T;
  documentsAndFolders?: T;
  folderType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Site-wide header: navigation, mega menus, and the CTA button.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom' | 'modal') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'insights';
                value: number | Insight;
              } | null);
          url?: string | null;
          /**
           * Opens this form in a modal drawer instead of navigating.
           */
          modalForm?: (number | null) | Form;
          label: string;
        };
        /**
         * Temporarily remove this item from the nav without deleting it.
         */
        hidden?: boolean | null;
        hasMegaMenu?: boolean | null;
        megaMenu?: {
          panelLabel: string;
          panelHeadline: string;
          panelDescription?: string | null;
          rightTitle: string;
          rightSubtitle?: string | null;
          items?:
            | {
                /**
                 * Material Symbols icon name e.g. storefront, handshake, campaign, rocket_launch
                 */
                icon?: string | null;
                title: string;
                description?: string | null;
                link?: {
                  type?: ('reference' | 'custom' | 'modal') | null;
                  newTab?: boolean | null;
                  reference?:
                    | ({
                        relationTo: 'pages';
                        value: number | Page;
                      } | null)
                    | ({
                        relationTo: 'insights';
                        value: number | Insight;
                      } | null);
                  url?: string | null;
                  /**
                   * Opens this form in a modal drawer instead of navigating.
                   */
                  modalForm?: (number | null) | Form;
                };
                id?: string | null;
              }[]
            | null;
        };
        id?: string | null;
      }[]
    | null;
  cta: {
    label: string;
    type?: ('custom' | 'modal') | null;
    url?: string | null;
    /**
     * Opens this form in a modal drawer instead of navigating.
     */
    modalForm?: (number | null) | Form;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Site-wide footer: nav columns, contact info, and CTA.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  /**
   * Short tagline shown below the logo.
   */
  brandDescription?: string | null;
  columns?:
    | {
        label: string;
        links?:
          | {
              link: {
                type?: ('reference' | 'custom' | 'modal') | null;
                newTab?: boolean | null;
                reference?:
                  | ({
                      relationTo: 'pages';
                      value: number | Page;
                    } | null)
                  | ({
                      relationTo: 'insights';
                      value: number | Insight;
                    } | null);
                url?: string | null;
                /**
                 * Opens this form in a modal drawer instead of navigating.
                 */
                modalForm?: (number | null) | Form;
                label: string;
              };
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  contactEmail?: string | null;
  /**
   * e.g. "Start a partnership"
   */
  contactCta?: string | null;
  contactCtaUrl?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Setting {
  id: number;
  /**
   * When enabled, robots.txt disallows all crawlers. Takes precedence over the rules below. Turn off when the site is ready to go public.
   */
  noIndex?: boolean | null;
  /**
   * Per-agent rules applied when "Block all crawlers" is off. Each entry maps one User-agent to allow/disallow paths.
   */
  robotsRules?:
    | {
        userAgent: string;
        allow?:
          | {
              path: string;
              id?: string | null;
            }[]
          | null;
        disallow?:
          | {
              path: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Your GA4 Measurement ID (e.g. G-XXXXXXXXXX). Leave empty to disable analytics.
   */
  googleAnalyticsId?: string | null;
  /**
   * When enabled, /llms.txt is publicly accessible and lists site content for AI agents.
   */
  llmsEnabled?: boolean | null;
  /**
   * Short description of the site shown at the top of llms.txt.
   */
  llmsSiteDescription?: string | null;
  /**
   * Include published pages in llms.txt.
   */
  llmsIncludePages?: boolean | null;
  /**
   * Include published insights (posts) in llms.txt.
   */
  llmsIncludeInsights?: boolean | null;
  /**
   * API key for the JotForm submissions API (used by the Claims refund flow). Only visible to logged-in admin users — never exposed in the public Settings API response.
   */
  jotformApiKey?: string | null;
  /**
   * Target JotForm form ID for the Claims refund flow. Leave empty to use the production "Amerikiosks - Refund Request" form (230405763622148) — override here to point at a clone/test form in local or staging.
   */
  jotformFormId?: string | null;
  /**
   * API token for the Monday.com GraphQL API (used by the Claims refund flow). Only visible to logged-in admin users — never exposed in the public Settings API response.
   */
  mondayApiToken?: string | null;
  /**
   * Where new refund claims sync to by default when submitted from the public ClaimForm. Changing this takes effect immediately for claims created after the change — existing claims keep whatever target they already have. Staff can still override a specific claim's target afterward in Claims → Integration target, but that only affects future re-syncs, not one already dispatched.
   */
  defaultClaimIntegrationTarget?: ('jotform' | 'odoo' | 'monday') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              modalForm?: T;
              label?: T;
            };
        hidden?: T;
        hasMegaMenu?: T;
        megaMenu?:
          | T
          | {
              panelLabel?: T;
              panelHeadline?: T;
              panelDescription?: T;
              rightTitle?: T;
              rightSubtitle?: T;
              items?:
                | T
                | {
                    icon?: T;
                    title?: T;
                    description?: T;
                    link?:
                      | T
                      | {
                          type?: T;
                          newTab?: T;
                          reference?: T;
                          url?: T;
                          modalForm?: T;
                        };
                    id?: T;
                  };
            };
        id?: T;
      };
  cta?:
    | T
    | {
        label?: T;
        type?: T;
        url?: T;
        modalForm?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  brandDescription?: T;
  columns?:
    | T
    | {
        label?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    modalForm?: T;
                    label?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  contactEmail?: T;
  contactCta?: T;
  contactCtaUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  noIndex?: T;
  robotsRules?:
    | T
    | {
        userAgent?: T;
        allow?:
          | T
          | {
              path?: T;
              id?: T;
            };
        disallow?:
          | T
          | {
              path?: T;
              id?: T;
            };
        id?: T;
      };
  googleAnalyticsId?: T;
  llmsEnabled?: T;
  llmsSiteDescription?: T;
  llmsIncludePages?: T;
  llmsIncludeInsights?: T;
  jotformApiKey?: T;
  jotformFormId?: T;
  mondayApiToken?: T;
  defaultClaimIntegrationTarget?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSyncClaimToIntegration".
 */
export interface TaskSyncClaimToIntegration {
  input: {
    claimId: number;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'insights';
          value: number | Insight;
        } | null);
    global?: string | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerBlock".
 */
export interface BannerBlock {
  style: 'info' | 'warning' | 'error' | 'success';
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'banner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CodeBlock".
 */
export interface CodeBlock {
  language?: ('typescript' | 'javascript' | 'css') | null;
  code: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'code';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}